#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "overleaf"
name = "Overleaf"
description.en = "Online real-time collaborative LaTeX editor"
description.fr = "Éditeur LaTeX collaboratif en ligne et en temps réel"

version = "2026.05.01~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later"
website = "https://www.overleaf.com"
userdoc = "https://www.overleaf.com/learn"
code = "https://github.com/overleaf/overleaf"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap = false
sso = false

disk = "3G"
ram.build = "1G"
ram.runtime = "1G"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/Thovi98/overleaf-builds/releases/download/20260501-c678859/overleaf_20260501-c678859.tar.gz"
    sha256 = "72138d6146173d14ca64b977538f3e44eb6bf2f6c43b13816f0647a5f1f6bea6"
    
    autoupdate.upstream = "https://github.com/Thovi98/overleaf-builds"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "([0-9]{4})([0-9]{2})([0-9]{2})"
    autoupdate.asset = ".*.tar.gz"

    [resources.sources.texlive]
    url = "https://texlive.info/historic/systems/texlive/2026/install-tl-unx.tar.gz"
    sha256 = "5cc0703d6fe49f00a2932c4e3bcee37a11cc0a969ae9fcbf9cad6f0d984d6363"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "compiles", "output", "cache", "user_files", "template_files", "history" ]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    admin.url = "/launchpad"
    admin.allowed = "admins"
    admin.show_tile = false

    [resources.ports]
    main.default = 8095
    #chat.default = 3010
    #clsi.default = 3013
    #contacts.default = 3036
    #docstore.default = 3016
    #docupdater.default = 3003
    #filestore.default = 3009
    #v1_history.default = 3100
    #notifications.default = 3042
    #project_history.default = 3054
    #realtime.default = 3026
    download.default = 8080

    [resources.apt]
    packages = [
        # Overleaf dependencies
       "redis-server", "python3-pygments",
        
       # Filestore dependencies
       "ghostscript", "optipng", "iproute2",

       # clsi dependencies
       "poppler-utils",
    ]

    [resources.nodejs]
    version = "22.18"
