  # handle output files for specific users
  location ~ ^__PATH__/project/([0-9a-f]+)/user/([0-9a-f]+)/build/([0-9a-f-]+)/output/(.+)$ {
    rewrite ^__PATH__/project/([0-9a-f]+)/user/([0-9a-f]+)/build/([0-9a-f-]+)/output/(.+)$ /$4 break;
    root __DATA_DIR__/output/$1-$2/generated-files/$3/;
  }
  # handle output files for anonymous users
  location ~ ^__PATH__/project/([0-9a-f]+)/build/([0-9a-f-]+)/output/(.+)$ {
    rewrite ^__PATH__/project/([0-9a-f]+)/build/([0-9a-f-]+)/output/(.+)$ /$3 break;
    root __DATA_DIR__/output/$1/generated-files/$2/;
  }

  # PDF range for specific users
  location ~ ^__PATH__/project/([0-9a-f]+)/user/([0-9a-f]+)/content/([0-9a-f-]+/[0-9a-f]+)$ {
    # Cache for one day
    expires 1d;
    alias __DATA_DIR__/output/$1-$2/content/$3;
  }
  # PDF range for anonymous users
  location ~ ^__PATH__/project/([0-9a-f]+)/content/([0-9a-f-]+/[0-9a-f]+)$ {
    # Cache for one day
    expires 1d;
    alias __DATA_DIR__/output/$1/content/$2;
  }