#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;

	root __INSTALL_DIR__/live/services/web/public/;

  client_max_body_size 50m;

	# block external access to prometheus /metrics
	location __PATH__/metrics/ {
		internal;
	}

	location __PATH__/ {
		proxy_pass http://127.0.0.1:__PORT__;
		include proxy_params_no_auth;
		
		proxy_read_timeout 10m;
		proxy_send_timeout 10m;
	}

	location __PATH__/socket.io/ {
		proxy_pass http://127.0.0.1:__PORT_REALTIME__;
		include proxy_params_no_auth;

		proxy_read_timeout 10m;
		proxy_send_timeout 10m;
	}

	location __PATH__/stylesheets/ {
		expires 1y;
	}

	location __PATH__/minjs/ {
		expires 1y;
	}

	location __PATH__/img {
		expires 1y;
	}

  # handle output files for specific users
  location ~ ^__PATH__/project/([0-9a-f]+)/user/([0-9a-f]+)/build/([0-9a-f-]+)/output/output\.([a-z.]+)$ {
		proxy_pass http://127.0.0.1:__PORT_DOWNLOAD__; # clsi-nginx.conf
		include proxy_params_no_auth;
  }
  # handle output files for anonymous users
  location ~ ^__PATH__/project/([0-9a-f]+)/build/([0-9a-f-]+)/output/output\.([a-z.]+)$ {
		proxy_pass http://127.0.0.1:__PORT_DOWNLOAD__; # clsi-nginx.conf
		include proxy_params_no_auth;
  }
  # PDF range for specific users
  location ~ ^__PATH__/project/([0-9a-f]+)/user/([0-9a-f]+)/content/([0-9a-f-]+/[0-9a-f]+)$ {
		proxy_pass http://127.0.0.1:__PORT_DOWNLOAD__; # clsi-nginx.conf
		include proxy_params_no_auth;
  }
  # PDF range for anonymous users
  location ~ ^__PATH__/project/([0-9a-f]+)/content/([0-9a-f-]+/[0-9a-f]+)$ {
		proxy_pass http://127.0.0.1:__PORT_DOWNLOAD__; # clsi-nginx.conf
		include proxy_params_no_auth;
  }

  # block external access to metrics
  location ~* ^__PATH__/metrics/?$ {
    return 404 'Not found';
  }

  # block external access to all health checks /health_check, /health_check/full, etc
  location ~* ^__PATH__/health_check {
    return 404 'Not found';
  }