#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup "$data_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup "/etc/systemd/system/$app-chat.service"
ynh_backup "/etc/systemd/system/$app-clsi.service"
ynh_backup "/etc/systemd/system/$app-contacts.service"
ynh_backup "/etc/systemd/system/$app-docstore.service"
ynh_backup "/etc/systemd/system/$app-document-updater.service"
ynh_backup "/etc/systemd/system/$app-filestore.service"
ynh_backup "/etc/systemd/system/$app-history-v1.service"
ynh_backup "/etc/systemd/system/$app-notifications.service"
ynh_backup "/etc/systemd/system/$app-project-history.service"
ynh_backup "/etc/systemd/system/$app-real-time.service"
ynh_backup "/etc/systemd/system/$app-web.service"

#=================================================
# BACKUP THE MONGODB DATABASE
#=================================================
ynh_print_info "Backing up the MongoDB database..."

ynh_mongo_dump_db --database=$app  > ./dump.bson

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
