#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-chat" >/dev/null; then
    yunohost service remove "$app-chat"
fi
ynh_config_remove_systemd "$app-chat"

if ynh_hide_warnings yunohost service status "$app-clsi" >/dev/null; then
    yunohost service remove "$app-clsi"
fi
ynh_config_remove_systemd "$app-clsi"

if ynh_hide_warnings yunohost service status "$app-contacts" >/dev/null; then
    yunohost service remove "$app-contacts"
fi
ynh_config_remove_systemd "$app-contacts"

if ynh_hide_warnings yunohost service status "$app-docstore" >/dev/null; then
    yunohost service remove "$app-docstore"
fi
ynh_config_remove_systemd "$app-docstore"

if ynh_hide_warnings yunohost service status "$app-document-updater" >/dev/null; then
    yunohost service remove "$app-document-updater"
fi
ynh_config_remove_systemd "$app-document-updater"

if ynh_hide_warnings yunohost service status "$app-filestore" >/dev/null; then
    yunohost service remove "$app-filestore"
fi
ynh_config_remove_systemd "$app-filestore"

if ynh_hide_warnings yunohost service status "$app-history-v1" >/dev/null; then
    yunohost service remove "$app-history-v1"
fi
ynh_config_remove_systemd "$app-history-v1"

if ynh_hide_warnings yunohost service status "$app-notifications" >/dev/null; then
    yunohost service remove "$app-notifications"
fi
ynh_config_remove_systemd "$app-notifications"

if ynh_hide_warnings yunohost service status "$app-project-history" >/dev/null; then
    yunohost service remove "$app-project-history"
fi
ynh_config_remove_systemd "$app-project-history"

if ynh_hide_warnings yunohost service status "$app-real-time" >/dev/null; then
    yunohost service remove "$app-real-time"
fi
ynh_config_remove_systemd "$app-real-time"

if ynh_hide_warnings yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi
ynh_config_remove_systemd "$app-web"

ynh_config_remove_nginx

ynh_systemctl --service=mongod --action=stop --wait_until="Shutting down" --log_path="/var/log/mongodb/mongod.log"
ynh_replace --match="replication:" --replace="#replication:" --file="/etc/mongod.conf"
ynh_replace --match=" replSetName: $app" --replace="" --file="/etc/mongod.conf"
ynh_systemctl --service=mongod --action=start --wait_until="aiting for connections" --log_path="/var/log/mongodb/mongod.log"

ynh_mongo_remove_db --db_user=$db_user --db_name=$db_name
ynh_remove_mongo

ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
