#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_nodejs_install
ynh_install_mongo

#=================================================
# RESTORE THE MONGODB DATABASE
#=================================================
ynh_script_progression "Restoring the MongoDB database..."

ynh_mongo_restore_db --database=$app < ./dump.bson

if ynh_hide_warnings ynh_mongo_exec --command="printjson(rs.status())" | grep -q "not running with --replSet"; then
	ynh_systemctl --service=mongod --action=stop --wait_until="Shutting down" --log_path="/var/log/mongodb/mongod.log"
	ynh_replace --match="#replication:" --replace="replication:\n  replSetName: $app" --file="/etc/mongod.conf"
	ynh_systemctl --service=mongod --action=start --wait_until="aiting for connections" --log_path="/var/log/mongodb/mongod.log"
	ynh_mongo_exec --command="rs.initiate()"
fi

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-chat.service"
systemctl enable "$app-chat.service" --quiet
yunohost service add "$app-chat" --log="/var/log/$app/chat.log"

ynh_restore "/etc/systemd/system/$app-clsi.service"
systemctl enable "$app-clsi.service" --quiet
yunohost service add "$app-clsi" --log="/var/log/$app/clsi.log"

ynh_restore "/etc/systemd/system/$app-contacts.service"
systemctl enable "$app-contacts.service" --quiet
yunohost service add "$app-contacts" --log="/var/log/$app/contacts.log"

ynh_restore "/etc/systemd/system/$app-docstore.service"
systemctl enable "$app-docstore.service" --quiet
yunohost service add "$app-docstore" --log="/var/log/$app/docstore.log"

ynh_restore "/etc/systemd/system/$app-document-updater.service"
systemctl enable "$app-document-updater.service" --quiet
yunohost service add "$app-document-updater" --log="/var/log/$app/document-updater.log"

ynh_restore "/etc/systemd/system/$app-filestore.service"
systemctl enable "$app-filestore.service" --quiet
yunohost service add "$app-filestore" --log="/var/log/$app/filestore.log"

ynh_restore "/etc/systemd/system/$app-history-v1.service"
systemctl enable "$app-history-v1.service" --quiet
yunohost service add "$app-history-v1" --log="/var/log/$app/history-v1.log"

ynh_restore "/etc/systemd/system/$app-notifications.service"
systemctl enable "$app-notifications.service" --quiet
yunohost service add "$app-notifications" --log="/var/log/$app/notifications.log"

ynh_restore "/etc/systemd/system/$app-project-history.service"
systemctl enable "$app-project-history.service" --quiet
yunohost service add "$app-project-history" --log="/var/log/$app/project-history.log"

ynh_restore "/etc/systemd/system/$app-real-time.service"
systemctl enable "$app-real-time.service" --quiet
yunohost service add "$app-real-time" --log="/var/log/$app/real-time.log"

ynh_restore "/etc/systemd/system/$app-web.service"
systemctl enable "$app-web.service" --quiet
yunohost service add "$app-web" --log="/var/log/$app/web.log"

mkdir -p "/var/log/$app"
chown -R $app:$app "/var/log/$app"
ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-chat" --action="start" --log_path="/var/log/$app/chat.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-clsi" --action="start" --log_path="/var/log/$app/clsi.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-contacts" --action="start" --log_path="/var/log/$app/contacts.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-docstore" --action="start" --log_path="/var/log/$app/docstore.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-document-updater" --action="start" --log_path="/var/log/$app/document-updater.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-filestore" --action="start" --log_path="/var/log/$app/filestore.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-history-v1" --action="start" --log_path="/var/log/$app/history-v1.log" --wait_until="Loading backend"
ynh_systemctl --service="$app-notifications" --action="start" --log_path="/var/log/$app/notifications.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-project-history" --action="start" --log_path="/var/log/$app/project-history.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-real-time" --action="start" --log_path="/var/log/$app/real-time.log" --wait_until="Using settings from"
ynh_systemctl --service="$app-web" --action="start" --log_path="/var/log/$app/web.log" --wait_until="listening on" --wait_until="Using settings from"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
